apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-configmap
  labels:
    name: kibana-configmap
data:
  config: |-
    server.host: '0.0.0.0'
    elasticsearch.url: 'http://elasticsearch:9200'

